### ISSUE TITLE
More Recipes from another Site (https://film.recipes/)

### ISSUE THREAD

**Issue by yitchee** [plamf/fuji-x-weekly-simulation-profiles#1]
Hey, really like this tool, very helpful for testing which ones I want on my camera!

There's another site with more recipes that you could add to this - [film.recipes](https://film.recipes/). Some are similar but there's quite a few new ones I haven't seen on FujiXWeekly.

**Comment by plamf** [comment]
I will include those recipes as soon as I get around to parse the recipes from the site listed in [this issue](https://github.com/plamf/fuji-x-weekly-simulation-profiles/issues/2)
