### ISSUE TITLE
Apostrophe in "Reggie's Portra" XML causes X Raw Studio to hang

### ISSUE THREAD

**Issue by porkrind** [plamf/fuji-x-weekly-simulation-profiles#5]
The apostrophe in the XML title of the recipe (not in the filename) causes Reggie's Portra to not be selectable while editing images, and if you try to send that recipe to an open custom slot (X-S10 in this case, it fails and X Raw Pro hangs until the camera is turned off or disconnected.

**Comment by plamf** [comment]
Thanks for pointing this out. Turns out I fixed this issue when trying it out myself and then forgot to upload the fixed profile.

**Comment by plamf** [comment]
Fixed in [v1.1.3](https://github.com/plamf/fuji-x-weekly-simulation-profiles/releases/tag/v1.1.3)
