### ISSUE TITLE
Can't find the X_RAW_STUDIO folder on Mac

### ISSUE THREAD

**Issue by marvinknoll** [plamf/fuji-x-weekly-simulation-profiles#7]
Hello,

First of all, thank you for creating and maintaining this repository!

I'm having trouble finding the `X_RAW_STUDIO` folder on my Mac. According to the instructions, it should be located here: 

`~/Library/Application Support/com.fujifilm.denji/X_RAW_STUDIO`

However, I can't find 'com.fujifilm.denji' on my system. I have installed Fuji X RAW Studio and followed all the prerequisites, but the folder doesn't appear in the specified location.

Could you please provide more information or guidance on where to locate this folder or if there are any steps I might be missing?

Thank you again for your efforts and support!

**Comment by marvinknoll** [comment]
I found the solution! I was mistakenly searching in **/Library/Application Support/** instead of the correct path, which is **~/Application Support/**.

**Comment by plamf** [comment]
Only saw your comment just now. I'm glad you solved it! :)
